spring.application.name=Practice
spring.datasource.url=jdbc:mysql://localhost:3306/myblogapp
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update


#JWT CONFIG
#we can encrypt the value using sha 256 online tool
app.jwt-secret=09049a6d636459450583a07aef71ce427f69a6e72fc83b1e9bd81da428292ba1
app-jwt-expiration-milliseconds=345600000